### ISSUE TITLE
Converting currency amounts to USD value natively

### ISSUE THREAD

**Issue by Walledgarden** [tipccjs/tipcc.js#2]
This feature would improve the quality of the library, because people would have a native function in the Amount class which would convert the amount in the USD value by using the cached currencies.

`<#Amount>.toFiat(fiatCurrency defaults to USD)`

**Comment by ZeroWave022** [comment]
@Walledgarden can this be closed as https://github.com/tipccjs/tipcc.js/pull/19/commits/96a8f43b238d84eda4ddf9b41e4e59cc519e6969 is pushed?
