### ISSUE TITLE
Add Prettier for code formatting

### ISSUE THREAD

**Issue by ZeroWave022** [tipccjs/tipcc.js#5]
While everyone has their own coding style, using one code formatter with a configuration file will make sure everyone is following one code style.

**Comment by Walledgarden** [comment]
Actually, prettier is already installed and used, but not configured.

**Comment by ZeroWave022** [comment]
I see, any suggestions for the config file?

**Comment by Walledgarden** [comment]
I'm personally using those (for eslint and prettier). It would be proably smart adding the prettier plugin to the eslint config too.
If we mainly want to use prettier, we should make a more advanced config file tho.

`.prettierrc.json`
```shell
{
  "singleQuote": true
}
```

`.prettierignore`
```shell
# Ignore artifacts:
build
coverage
dist
```

`.eslintrc.js`
```js
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'import', 'prettier'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'airbnb-typescript/base',
  ],
  parserOptions: {
    project: './tsconfig.json',
  },
  ignorePatterns: ['dist/**/*.js'],
  rules: {
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
  },
};
```
